name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
          architecture: 'x64'

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Enable CI settings
        run: |
          echo "$GCS_SA_KEY" > key.json
          cat <<EOF >>.bazelrc
            common --config=ci
            build:ci --google_credentials=key.json
          EOF
        env:
          GCS_SA_KEY: ${{secrets.GCS_SA_KEY}}

      - name: Lint
        run: |
          ./lint.sh

      - name: Build all artifacts
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build //...
