name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
          architecture: 'x64'

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.cache/bazel
          key: bazel

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Enable CI settings
        run: |
          cat <<EOF >>.bazelrc
            common --config=ci
          EOF

      - name: Lint
        run: |
          ./lint.sh

      - name: Build all artifacts
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build //...
